# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-03 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180803_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coursetime',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='课时'),
        ),
    ]
