# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-08 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='nums',
            field=models.IntegerField(default=0, verbose_name='章节数'),
        ),
    ]
