# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-10 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='nums',
        ),
    ]
