# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-14 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_video_learn_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresource',
            name='name',
            field=models.CharField(max_length=100, verbose_name='资源名称'),
        ),
    ]
