# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-23 07:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 23, 15, 2, 39, 490601), verbose_name='添加时间'),
        ),
    ]
