# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-31 11:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20180726_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 31, 11, 55, 7, 59920), verbose_name='添加时间'),
        ),
    ]
