# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-01 14:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_auto_20180731_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 14, 16, 44, 974042), verbose_name='添加时间'),
        ),
    ]
