# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-03 11:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_auto_20180801_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 3, 11, 18, 49, 710031), verbose_name='添加时间'),
        ),
    ]
