# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-03 16:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_auto_20180803_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 3, 16, 48, 54, 992004), verbose_name='添加时间'),
        ),
    ]
