# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-10 11:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0012_auto_20180808_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 10, 11, 28, 3, 464285), verbose_name='添加时间'),
        ),
    ]
