# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-10 11:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0013_auto_20180810_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 10, 11, 40, 21, 785417), verbose_name='添加时间'),
        ),
    ]
