# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-14 14:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0020_auto_20180814_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 14, 14, 55, 30, 199668), verbose_name='添加时间'),
        ),
    ]
