# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-14 16:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0022_auto_20180814_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 14, 16, 19, 17, 850876), verbose_name='添加时间'),
        ),
    ]
