# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-15 17:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0023_auto_20180814_1619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCouser',
            new_name='UserCourse',
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 15, 17, 21, 35, 167877), verbose_name='添加时间'),
        ),
    ]
